name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SKIP_DB_BOOT: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl

      - name: Install PHP Dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: |
          php artisan key:generate --show --no-interaction

      - name: Install npm and Build Assets
        run: |
          rm -rf node_modules package-lock.json 
          npm install
          npm run build

      - name: Create ZIP File
        run: |
          mkdir deploy
          zip -r deploy/archive.zip ./* -x ".git/*" ".github/*" "node_modules/*" ".env" "storage/*"

      - name: Upload ZIP File via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.emadparibahan.com.bd
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: /public_html/portfolio  # Use root since your hostname points here

      - name: Trigger Unzipper Script
        run: |
          curl -X GET "https://mdshahidul.com/unzipper.php"

      - name: Run Migrations
        run: |
          curl -X GET "https://mdshahidul.com/migrate?key=${{ secrets.MIGRATION_KEY }}"
